MAINT: Restore numpydoc
mne-tools/mne-nirs pull request #355
Opened 2021-08-16 17:03 UTC by larsoner

Follow-up to #351

2021-08-16 21:39 UTC, larsoner commented on .github/workflows/CircleCI_PR.yml
> +  cancel-in-progress: true
I also added concurrency groups which make it so that running actions auto-kills any existing runs for a given PR

2021-08-16 22:14 UTC, rob-luke commented on .github/workflows/CircleCI_PR.yml
> +  cancel-in-progress: true
Ah! I had been wondering what this did in the MNE-Python repo, thanks for explaining, that's a great feature.

2021-08-16 22:21 UTC, rob-luke requested changes
First off, THANK YOU @larsoner. You've touched many things that I have been pulling my hair out about. I really want to get numpydoc working again, I appreciate your help.

2021-08-16 22:21 UTC, rob-luke commented on doc/api.rst
> -   ContrastResults.save
I really want to have these methods listed on the API page. Many users will be new to programming and won't understand about classes etc. So I fear that they will come to the API page, hit ctrl-f and search for "region", it will return nothing, and they will leave. Is there any way this is possible?

If not possible (which would make me sad), I would like to list them in plain text and point the user to look in the sub-api pages, so that the terms pop up in a ctrl-f search.

Thoughts?

2021-08-16 22:48 UTC, larsoner commented on doc/api.rst
> -   ContrastResults.save
You should look at how scipy does it. It's not as easy as what MNE does but it does what you want I think. Personally I think the search box plus example linking is good enough for discoverability that this probably isn't really an issue for many folks but that's just speculation on my part

2021-08-16 22:50 UTC, larsoner commented on doc/api.rst
> -   ContrastResults.save
Actually I'm not even sure if SciPy's allows listing them separately, even there I think they're only listed on the class's page.

One option would be too keep this but use a noindex template. I can try implementing that tomorrow...

2021-08-17 00:00 UTC, larsoner commented
This seems to do the right thing:

https://1668-254026779-gh.circle-artifacts.com/0/dev/pull/355/api.html#statistics

2021-08-17 00:26 UTC, rob-luke commented
This is just perfect. I love it. Thanks @larsoner

2021-08-17 00:26 UTC, merged