ENH: plot_3d_montage
mne-tools/mne-nirs pull request #442
Opened 2022-02-04 20:52 UTC by larsoner

Code is getting there. If MNE-Python's montage functions are used, autodetection works:
```
    view_map = {
        'left-lat': np.arange(1, 13),
        'right-lat': np.arange(13, 25),
    }
    fig = mne_nirs.visualisation.plot_3d_montage(
        use['h'].info, view_map=view_map, subjects_dir=subjects_dir)
```
![montage](https://user-images.githubusercontent.com/2365790/152600237-69e592c6-2b61-4580-b448-41f76427fb20.png)

NIRx doesn't use the same positions as the builtin MNE-Python montage, so we need to do more for this case:
```
    view_map = {
        'left-lat': np.r_[np.arange(1, 13),
                          np.arange(58, 74),
                          np.arange(75, 78)],
        'caudal': np.r_[42,
                        np.arange(45, 58),
                        74,
                        np.arange(78, 85)],
        'right-lat': np.r_[np.arange(13, 42), 43, 44],
    }
    fig = mne_nirs.visualisation.plot_3d_montage(
        info, view_map=view_map, subjects_dir=subjects_dir)
```

![montage](https://user-images.githubusercontent.com/2365790/152600345-b3d697d7-ef64-4b37-a4e6-c914a5c2f2ca.png)

The modified example has the same problem:
```
view_map = {
    'left-lat': np.r_[np.arange(1, 27), 28],
    'caudal': np.r_[27, np.arange(43, 53)],
    'right-lat': np.r_[np.arange(29, 43), 44],
}

fig = mne_nirs.visualisation.plot_3d_montage(
    raw.info, view_map=view_map, subjects_dir=subjects_dir)
```
![Screenshot from 2022-02-04 15-40-10](https://user-images.githubusercontent.com/2365790/152600391-3d09d276-b9d3-4fc1-8370-95f987ec2f67.png)

# Todo

- [ ] Fix NIRx 10-20 detection
- [ ] Add tests

## Option 1

@rob-luke one option would be to make a function for NIRx that converts their 10-20 positions to MNE-Python's. Do they have standard 10-20 positions that then populate `info`? If so, we could come up with a lookup table, then people can do:
```
mne_nirs.something.convert_nirx_1020(raw.info, copy=False)
```
to update their channel positions. Users can even avoid making it permanent just by doing in their code before plotting:
```
plot_info = mne_nirs.something.convert_nirx_1020(raw.info)  # default is copy=True
mne_nirs.visualisation.plot_3d_montage(plot_info, ...)
```

## Option 2

Another clean way to go would be, instead of `'auto'`, the default value could be `src_det_names='standard_1020'` to give a montage to load. Then in MNE-Python we can add a `'nirx'` named montage, so then the call here would be `src_det_names='nirx'` or so. Or we just make `nirx_montage = mne_nirs.something.get_montage('nirx')` that you can then pass directly as `src_det_names=nirx_montage` to tell it which positions to look at to get the names.

I think my vote is for Option 2, because it nicely generalizes. You could imagine generalizing to `get_montage('flow')` or so. And then `src_det_names=<str>` could by convenience call the mne_nirs get_montage first, and if it doesn't exist, try loading the MNE-Python get_montage (like standard_1020)... and we could maybe even make `auto` detect the acq system and triage to the correct one (standard_1020 for Hitachi, nirx for nirx, flow for kernel flow, etc.).

2022-02-04 21:11 UTC, larsoner commented on mne_nirs/visualisation/_plot_3d_montage.py
> +        *numbers*, the values should be 1-based rather than 0-based.
I also need to actually describe the options here (hemi-brainview keys)

2022-02-07 00:41 UTC, rob-luke commented
This looks really cool @larsoner 

> @rob-luke one option would be to make a function for NIRx that converts their 10-20 positions to MNE-Python's. Do they have standard 10-20 positions that then populate info? 

You can place your optode positions anywhere in a NIRX system, you are not restricted to 10-20 style locations. When i've built my montages I just click as close to the 10-20 positions as I can.  So there is not a direct mapping, does this make sense?

But in general, the NIRS community haven't used these standard positions as much as they could (and I have received much critisim in manuscript reviews for describing locations using "eeg" language). But I hope in the future the fNIRS community adopts standard locations more.

As most devices dont restrict users to 10-20 positions, I dont know if your option 2 will work. Instead of specifying positions using 10-20 naming, all the fNIRS data files I have used specify the locations using 3D coordinates. But I guess when using `auto` we could try and detect a standard position name, and if the distance/error is too great then just revert to the uninformative naming of `S1` etc? I dont knot if I am being helpful here or not.

2022-02-07 15:54 UTC, larsoner commented
> When i've built my montages I just click as close to the 10-20 positions as I can. So there is not a direct mapping, does this make sense?

Ahh so even if in experiment 1 you placed an electrode on the participant and clicked in their GUI as close to Cz as you can, these two could (probably will) end up with different X/Y/Z coordinates? Then in this case I think the solution here is probably all we want -- if the electrode positions match the standard MNE 10-20, use 10-20 names, otherwise rely on the user to either 1) `set_montage` using the MNE standard 10-20 locations if they want to standardize or 2) pass a mapping dict directly to say what S1, S2, ..., D1, D2, ... map to.

I'll move on to writing some tests and improving the docstring, then I think that's probably sufficient for this first PR.

2022-02-08 00:05 UTC, rob-luke commented
> Ahh so even if in experiment 1 you placed an electrode on the participant and clicked in their GUI as close to Cz as you can, these two could (probably will) end up with different X/Y/Z coordinates? 

Correct. But I do this only once per project/montage, then apply the same montage to all measurements within a single experiment.

> Any objection to adding an alias mne_nirs.viz that's the same as mne_nirs.visualisation? It bypasses the british/american English issue

I would have gone with vis 😉 But I agree we should go with viz for consistency with MNE etc

Ping me when its ready for review

2022-02-08 00:13 UTC, larsoner commented
Okay @rob-luke this is ready for review/merge from my end

2022-02-08 01:25 UTC, rob-luke requested changes
Thanks @larsoner

2022-02-08 01:25 UTC, rob-luke commented on mne_nirs/visualisation/_plot_3d_montage.py
> +    src_det_names : None | dict | str
Could you please add another example to the docs that uses the explicit setting of names via dict? Can be just directly below the existing example.

2022-02-08 16:39 UTC, larsoner commented
@rob-luke done!

https://2158-254026779-gh.circle-artifacts.com/0/dev/generated/mne_nirs.visualisation.plot_3d_montage.html#mne_nirs.visualisation.plot_3d_montage

2022-02-09 00:08 UTC, rob-luke commented
This is so great. Thanks @larsoner

2022-02-09 00:36 UTC, rob-luke commented
Just added a changelog entry. Merging now, thanks.

2022-02-09 00:36 UTC, merged

2022-02-09 00:38 UTC, larsoner commented
Feel free to make it better. In particular, the short channel plotting is a bit ugly. Might want some way to disable short channel labeling, or maybe show it differently somehow...

2022-02-09 01:12 UTC, rob-luke commented
Good ideas!