Write optical density data in SNIRF format
mne-tools/mne-nirs pull request #511
Opened 2023-04-28 12:44 UTC by florin-pop

Write optical density data in SNIRF format.. Work in progress..

2023-05-02 05:48 UTC, rob-luke commented
Great PR @florin-pop. I made some suggestions that I think will simplify the code and slightly boost test coverage. Could you please check if they actually work? And add a changelog entry then ping us for a review/merge. Thanks!

2023-05-02 05:48 UTC, rob-luke requested changes

2023-05-02 05:48 UTC, rob-luke commented on mne_nirs/io/snirf/_snirf.py
> +        raise ValueError('Data must be fnirs_cw_amplitude or fnirs_od')
I believe this will have the same effect and save writing a test for the else case.
```suggestion
    picks = _picks_to_idx(raw.info, ['fnirs_cw_amplitude', 'fnirs_od'], exclude=[])
    assert len(picks) == len(raw.ch_names),\
        'Data must only be of type fnirs_cw_amplitude or fnirs_od'
    assert len(np.unique(raw.info.get_channel_types())) == 1,\
        'All channels must be of the same type'
```

2023-05-02 05:48 UTC, rob-luke commented on mne_nirs/io/snirf/_snirf.py
> +        # 1 = Continuous Wave, 99999 = Processed
```suggestion
        # The data type coding is described at
        # https://github.com/fNIRS/snirf/blob/master/snirf_specification.md#appendix
        # The currently implemented data types are:
        # 1 = Continuous Wave
        # 99999 = Processed
```

2023-05-02 05:48 UTC, rob-luke commented on mne_nirs/io/snirf/_snirf.py
> +        data_type = 1 if 'fnirs_cw_amplitude' in raw else 99999
Nice! Very clean

2023-05-02 05:48 UTC, rob-luke commented on mne_nirs/io/snirf/tests/test_snirf.py
> +                       od.annotations.description)
```suggestion
    assert_array_equal(od_orig.annotations.description,
                       od.annotations.description)
    assert_array_equal(od_orig.get_data(), od.get_data())
```

2023-05-02 08:39 UTC, florin-pop commented
@larsoner I noticed that after you merged https://github.com/mne-tools/mne-python/pull/11665 this line started failing in CI https://github.com/mne-tools/mne-nirs/blob/975b44a1888e9b8173df7a2f718035e409d79b06/mne_nirs/statistics/tests/test_glm_type.py#L114
Should we replace it with:
`with pytest.raises(ValueError, match='not present in the info'):`
?

2023-05-02 12:47 UTC, florin-pop commented
I was thinking of doing something like:

```
    if check_version(mne.__version__, '1.4.0'):
        expected_pick_failure = ValueError
    else:
        expected_pick_failure = Warning
    with pytest.raises(expected_pick_failure, match='could not be picked'):
        assert len(res.copy().pick(picks=["S1_D1 hbr", "S1_D1 XXX"])) == 1

```

but I'm not sure `check_version` works as expected

```
>>> import mne
>>> from mne.utils import check_version
>>> print(mne.__version__)
1.4.0.dev136+g263114e32
>>> print(check_version(mne.__version__, '1.4.0', return_version=True))
(False, None)
```

2023-05-02 18:06 UTC, larsoner commented
I would use `mne.fixes._compare_version` since it behaves as you'd expect/need here, and the pattern I usually use is:
```
if _compare_version(mne.__version__, '>=', '1.4'):
    ctx = pytest.raises(ValueError, match='...')
else:
    ctx = pytest.warns(RuntimeWarning, match='...')
with ctx:
    ...
```

2023-05-03 05:25 UTC, rob-luke commented
Tests are green. Thanks @florin-pop @larsoner

2023-05-03 05:25 UTC, merged